dist: trusty
sudo: required
services:
  - docker
language: go
go:
  - 1.13
env:
  - GO111MODULE=on

script:
- make lint
- make test
- make vet

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
